### ISSUE TITLE
BotW Graphic Pack Day Length Mod Issue

### ISSUE THREAD

**Issue by Peduls** [ActualMandM/cemu_graphic_packs#483]
When trying to adjust the speed of time with the "Day Length" mod time doesn't actually move faster or slower. Appears to be broken.

**Comment by Crementif** [comment]
Fixed in https://github.com/ActualMandM/cemu_graphic_packs/commit/ca22977ef03e4a826f3bfe7f0df92447437c4219

**Comment by Peduls** [comment]
This is not fixed. I just tested with the latest graphic pack update.

**Comment by Peduls** [comment]
None of the "Day Length" setting have any effect on the clock and the "Freeze Time" option just makes the clouds freak out and time still progresses as normal.
